### PR TITLE
Alloc

### PR DESCRIPTION
**Pull request by hydroflame**

### CODE REVIEW

**Comment by sasha-s** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sudo_test.go, line 31 \[r1\]](https://reviewable.io:443/reviews/darkgopher/dark/2#-KPUm8yQ7XEVl21o1H-V:-KPUm8yRbEIXZqaUsj8Q:b-3rpm4g) ([raw file](https://github.com/darkgopher/dark/blob/df1d020478f348eb412850b5dc9e9f90b4d93855/sudo_test.go#L31)):*
> ```Go
> 	// Sudo the reflect.Value
> 	v = Sudo(v.FieldByName("x"))
> 	v.Set(reflect.ValueOf(int(2)))
> ```

Add an example without sudo that panics?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/darkgopher/dark/2)*

**Comment by hydroflame** [comment]
@sasha-s added

**Comment by sasha-s** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[sudo_test.go, line 37 \[r2\]](https://reviewable.io:443/reviews/darkgopher/dark/2#-KPUq-L7rL-IT4LsJZSW:-KPUq-L7rL-IT4LsJZSX:b-ut85nx) ([raw file](https://github.com/darkgopher/dark/blob/56b61ae654e50b87efa1e5fa426da6e2f8c63bd9/sudo_test.go#L37)):*
> ```Go
> }
> 
> func ExampleSudo_Panic() {
> ```

Nit: rename to ExampleNoSudo_Panic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/darkgopher/dark/2)*

**Comment by sasha-s** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/darkgopher/dark/2)*

**Pull request merged**
